# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 214f68a8e22b12a5577d1c8bd0b44562ffbae4d8542c5c1189efa3685feb6cf234a81e84130f74056d8b964c07779eb770f4aaf8dcdd35dcc2aa6f50d60c4d93

test:
  secret_key_base: 23dbef7e840685b9057989114df104a8e3a138f88be879aa5bf51cd0879534f997d2b7afd6e9eb3b26ef24d4014f98694fb399e5e72ac78c657fa61f0024325d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
